({
  token: process.env.BOT_TOKEN,
  payment_token: process.env.PAYMENT_TOKEN,
  active: true,
  files: process.env.FILES_HOST,
  web: process.env.WEB_HOST,
  hook: process.env.BOT_HOOK,
  botUrl: process.env.BOT_URL,
  adminId: process.env.ADMIN_ID,
  drop_pending_updates: false,
  allowed_updates: [
    'chat_member',
    'callback_query',
    'edited_message',
    'edited_channel_post',
    'message',
    'channel_post',
    'pre_checkout_query',
    'shipping_query',
    'chat_join_request',
    'my_chat_member',
    'business_connection',
    'business_message',
    'edited_business_message',
    'deleted_business_messages',
    'message_reaction',
    'message_reaction_count',
    'inline_query',
    'chosen_inline_result',
    'purchased_paid_media',
    'poll',
    'poll_answer',
    'chat_boost',
    'removed_chat_boost',
  ],
  limits: {
    messages: 20,
  }
})