---
- name: Update server application
  hosts: all
  vars_files:
    - group_vars/all/vars.yml

  tasks:
    - name: Sync project files excluding sensitive files
      synchronize:
        src: "{{ local_path }}/application/"
        dest: "{{ remote_path }}/application"
        archive: yes
        recursive: yes
        owner: yes
        group: yes
        mode: push
        delete: yes
        rsync_opts:
          - "--chmod=755"
          - "--exclude=tasks/"
          - "--exclude=resources/"
          - "--exclude=cert/"
          - "--exclude=static/"
      become: yes

    - name: Show update info
      debug:
        msg: "Server application updated on {{ inventory_hostname }}"