({
  method: {
    post: 'sendInvoice',
    body: [
      'chat_id',
      'message_thread_id',
      'title',
      'description',
      'payload',
      'provider_token',
      'currency',
      'prices',
      'max_tip_amount',
      'suggested_tip_amounts',
      'start_parameter',
      'provider_data',
      'photo_url',
      'photo_size',
      'photo_width',
      'photo_height',
      'need_name',
      'need_phone_number',
      'need_email',
      'need_shipping_address',
      'send_phone_number_to_provider',
      'send_email_to_provider',
      'is_flexible',
      'disable_notification',
      'protect_content',
      'reply_parameters',
      'reply_markup',
    ],
  },
});